export const numbers = [
  {
    id: crypto.randomUUID(),
    num: 1,
    isShow: false,
    isFound: false,
  },
  {
    id: crypto.randomUUID(),
    num: 2,
    isShow: false,
    isFound: false,
  },
  {
    id: crypto.randomUUID(),
    num: 3,
    isShow: false,
    isFound: false,
  },
  {
    id: crypto.randomUUID(),
    num: 4,
    isShow: false,
    isFound: false,
  },
  {
    id: crypto.randomUUID(),
    num: 5,
    isShow: false,
    isFound: false,
  },
  {
    id: crypto.randomUUID(),
    num: 6,
    isShow: false,
    isFound: false,
  },
  {
    id: crypto.randomUUID(),
    num: 7,
    isShow: false,
    isFound: false,
  },
  {
    id: crypto.randomUUID(),
    num: 8,
    isShow: false,
    isFound: false,
  },
  {
    id: crypto.randomUUID(),
    num: 9,
    isShow: false,
    isFound: false,
  },
  {
    id: crypto.randomUUID(),
    num: 10,
    isShow: false,
    isFound: false,
  },
  {
    id: crypto.randomUUID(),
    num: 11,
    isShow: false,
    isFound: false,
  },
  {
    id: crypto.randomUUID(),
    num: 12,
    isShow: false,
    isFound: false,
  },
  {
    id: crypto.randomUUID(),
    num: 13,
    isShow: false,
    isFound: false,
  },
  {
    id: crypto.randomUUID(),
    num: 14,
    isShow: false,
    isFound: false,
  },
  {
    id: crypto.randomUUID(),
    num: 15,
    isShow: false,
    isFound: false,
  },
  {
    id: crypto.randomUUID(),
    num: 16,
    isShow: false,
    isFound: false,
  },
  {
    id: crypto.randomUUID(),
    num: 17,
    isShow: false,
    isFound: false,
  },
  {
    id: crypto.randomUUID(),
    num: 18,
    isShow: false,
    isFound: false,
  },
  {
    id: crypto.randomUUID(),
    num: 1,
    isShow: false,
    isFound: false,
  },
  {
    id: crypto.randomUUID(),
    num: 2,
    isShow: false,
    isFound: false,
  },
  {
    id: crypto.randomUUID(),
    num: 3,
    isShow: false,
    isFound: false,
  },
  {
    id: crypto.randomUUID(),
    num: 4,
    isShow: false,
    isFound: false,
  },
  {
    id: crypto.randomUUID(),
    num: 5,
    isShow: false,
    isFound: false,
  },
  {
    id: crypto.randomUUID(),
    num: 6,
    isShow: false,
    isFound: false,
  },
  {
    id: crypto.randomUUID(),
    num: 7,
    isShow: false,
    isFound: false,
  },
  {
    id: crypto.randomUUID(),
    num: 8,
    isShow: false,
    isFound: false,
  },
  {
    id: crypto.randomUUID(),
    num: 9,
    isShow: false,
    isFound: false,
  },
  {
    id: crypto.randomUUID(),
    num: 10,
    isShow: false,
    isFound: false,
  },
  {
    id: crypto.randomUUID(),
    num: 11,
    isShow: false,
    isFound: false,
  },
  {
    id: crypto.randomUUID(),
    num: 12,
    isShow: false,
    isFound: false,
  },
  {
    id: crypto.randomUUID(),
    num: 13,
    isShow: false,
    isFound: false,
  },
  {
    id: crypto.randomUUID(),
    num: 14,
    isShow: false,
    isFound: false,
  },
  {
    id: crypto.randomUUID(),
    num: 15,
    isShow: false,
    isFound: false,
  },
  {
    id: crypto.randomUUID(),
    num: 16,
    isShow: false,
    isFound: false,
  },
  {
    id: crypto.randomUUID(),
    num: 17,
    isShow: false,
    isFound: false,
  },
  {
    id: crypto.randomUUID(),
    num: 18,
    isShow: false,
    isFound: false,
  },
];
